spring:
  application:
    name: project-management
  datasource:
    url: jdbc:h2:mem:projectdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  mvc:
    throw-exception-if-no-handler-found: true
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIDI1Ni1iaXQgc2VjcmV0IGtleSBmb3IgdGVzdGluZw==
  expiration: 86400000 # 24 hours in milliseconds
  header: Authorization
  prefix: "Bearer " 